% validation_G_col1.nc
; Generated by s08_make_validation_nc.py
; Template: pressure_sweap_30-120_step-5.nc
; Recommendation: recommendation_G.csv
; Geometry: 2D cross-hatch grid | 3+3 strands | 2x2 open pores | single layer
; Temperature: set manually in Architect UI (not in G-code)
;
; Col 1  A1-F1   P=130 kPa  F=5 mm/s  Z=0.1 mm   V1 ML recommendation (cell_gelma_7_60)
;
; Model: M_full:Ridge
; Predicted SF_mean: 1.362008 +/- nan (unavailable (no --comparison_csv))
; Trained on: cell_gelma_10_60,cell_gelma_10_80,gelma_10_60,gelma_10_80
; Target SF values were NOT used to choose this condition.
;
; INITIALIZATION
T1
M200=1300 ; Set pressure to 130kPa
T0
G803 ; Move to safe height
; INITIALIZATION

M110=0 ; Set printing progress to 0%
T1
G801 ; Measure tool

#CONTOUR MODE ON [DEV PATH_DEV=0.08]

M312 ; Wait for work zone temperature

; -- V1 ML recommendation (cell_gelma_7_60): P=130 kPa  F=5 mm/s  Z=0.100 mm --
G805[-45.785, 32.720, 2.620] ; G55 origin: A1
G55

; Changing tool to 'PSD 1'
#FLUSH WAIT
T1
G807[1, 0.002, 0.002] ; time-based start/stop delays [s]
M200=1300 ; pressure 130kPa
F5.000
G00 X-2.000 Y-2.500
M151 ; Engage tool for printing
Z0.100
M110=23
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well A1
G805[-45.785, 19.640, 2.620] ; G55 origin: B1
G55
G00 Z18.400
M200=1300
F5.000
X-2.000 Y-2.500
Z0.100
M110=36
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well B1
G805[-45.785, 6.560, 2.620] ; G55 origin: C1
G55
G00 Z18.400
M200=1300
F5.000
X-2.000 Y-2.500
Z0.100
M110=50
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well C1
G805[-45.785, -6.520, 2.620] ; G55 origin: D1
G55
G00 Z18.400
M200=1300
F5.000
X-2.000 Y-2.500
Z0.100
M110=63
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well D1
G805[-45.785, -19.600, 2.620] ; G55 origin: E1
G55
G00 Z18.400
M200=1300
F5.000
X-2.000 Y-2.500
Z0.100
M110=76
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well E1
G805[-45.785, -32.680, 2.620] ; G55 origin: F1
G55
G00 Z18.400
M200=1300
F5.000
X-2.000 Y-2.500
Z0.100
M110=90
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well F1

; CAMERA IMAGING POSITIONS
; Wells: A1, B1, C1, D1, E1, F1
; Z safe = 40 mm  |  Z imaging = 20 mm
; ==========================================================

#FLUSH WAIT
#CONTOUR MODE OFF          ; Exit tracking mode from printing
#FLUSH WAIT

T1                         ; Select slot 1
G803                       ; Move to system safe height

; --- Well A1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y53.250              ; Move XY to A1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at A1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well B1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y40.242              ; Move XY to B1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at B1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well C1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y27.234              ; Move XY to C1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at C1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well D1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y14.226              ; Move XY to D1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at D1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well E1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y1.218              ; Move XY to E1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at E1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well F1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y-11.790              ; Move XY to F1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at F1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Return home ---
G00 G54 G90 Z40.000          ; Safe Z before going home
G800                       ; Go home
M110=1000
M30
