% validation_E_col2.nc
; Generated by s08_make_validation_nc.py
; Template: data_collection_48well_8cols_s0-s28.nc  (all geometry copied verbatim)
; Recommendation: recommendation_E.csv
;
; Col 2  A2-F2   P=93 kPa  F=5 mm/s  Z=0.1 mm   V1 ML recommendation (cell_gelma_10_60)
;
; Model: M_full:GPR
; Predicted SF_mean: 0.735949 +/- 0.068029 (GPR posterior sd)
; Trained on: cell_gelma_10_80,cell_gelma_7_60,cell_gelma_7_80,gelma_10_60,gelma_10_80,gelma_7_60,gelma_7_80
; Target SF values were NOT used to choose this condition.
;
; INITIALIZATION
T1
M200=930 ; pressure 93kPa
T0
G803 ; Move to safe height
; INITIALIZATION

M110=0 ; Set printing progress to 0%
T1
G801 ; Measure tool

#CONTOUR MODE ON [DEV PATH_DEV=0.08]

M312 ; Wait for work zone temperature

; -- V1 ML recommendation (cell_gelma_10_60): col 2  P=93 kPa  F=5 mm/s  Z=0.100 mm --
G805[-32.705, 32.720, 2.620] ; G55 origin: A2
G55

; Changing tool to 'PSD 1'
#FLUSH WAIT
T1
G807[1, 0.002, 0.002] ; time-based start/stop delays [s]
M200=930 ; pressure 93kPa
F5.000
G00 X-2.000 Y-2.500
M151 ; Engage tool for printing
Z0.100
M110=40
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well A2
G805[-32.705, 19.640, 2.620] ; G55 origin: B2
G55
G00 Z18.400
M200=930
F5.000
X-2.000 Y-2.500
Z0.100
M110=50
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well B2
G805[-32.705, 6.560, 2.620] ; G55 origin: C2
G55
G00 Z18.400
M200=930
F5.000
X-2.000 Y-2.500
Z0.100
M110=50
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well C2
G805[-32.705, -6.520, 2.620] ; G55 origin: D2
G55
G00 Z18.400
M200=930
F5.000
X-2.000 Y-2.500
Z0.100
M110=50
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well D2
G805[-32.705, -19.600, 2.620] ; G55 origin: E2
G55
G00 Z18.400
M200=930
F5.000
X-2.000 Y-2.500
Z0.100
M110=50
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well E2
G805[-32.705, -32.680, 2.620] ; G55 origin: F2
G55
G00 Z18.400
M200=930
F5.000
X-2.000 Y-2.500
Z0.100
M110=50
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well F2

; CAMERA IMAGING POSITIONS
; Wells: A2, B2, C2, D2, E2, F2
; Column-major order: col1 (A1-F1) -> col2 (A2-F2) -> ...
; Slot 1 selected (T1) -- camera physically at slot 5.
; Z safe = 40.0 mm  |  Z imaging = 20.0 mm
; ============================================================

#FLUSH WAIT
#CONTOUR MODE OFF          ; Exit tracking mode from printing
#FLUSH WAIT

T1                         ; Select slot 1
G803                       ; Move to system safe height

; --- Well A2 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-237.023 Y53.250              ; Move XY to A2
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at A2 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well B2 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-237.023 Y40.242              ; Move XY to B2
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at B2 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well C2 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-237.023 Y27.234              ; Move XY to C2
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at C2 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well D2 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-237.023 Y14.226              ; Move XY to D2
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at D2 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well E2 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-237.023 Y1.218              ; Move XY to E2
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at E2 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well F2 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-237.023 Y-11.790              ; Move XY to F2
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at F2 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Return home ---
G00 G54 G90 Z40.000          ; Safe Z before going home
G800                       ; Go home
M110=1000
M30
