% d5_B-F_cell_gelma_10_80_c1_freeopt_P108_F5_Z0p1_col1_n6
; Generated by s09_make_d5_transfer_nc.py
; Template : pressure_sweap_30-120_step-5.nc
; Source   : d5_optimum_movement.csv   (Part D, step D5)
;
; =============== WHAT TO LOAD ===============
; INK IN THE CARTRIDGE : cell_gelma_10_80    <-- CELL-LADEN
; Both conditions of this pair use this same cell-laden ink.
; Nothing in this experiment is printed cell-free.
; ============================================
;
; Pair         : B/F  (gelma_10_80 -> cell_gelma_10_80)
; Condition    : 1 of 2   [freeopt]
; Meaning      : optimum derived from the CELL-FREE dataset, printed in cell-laden ink
; Derived from : gelma_10_80 48-well data
;
; Pressure     : 108 kPa  -> M200=1080
; Nozzle speed : 5 mm/s -> F
; Z offset     : 0.1 mm
; Wells        : column 1, A1-F1 (6 replicates)
;
; Predicted SF on the cell-laden surface : 0.4909 +/- 0.0768
; Transfer regret for this pair          : 0.0912 SF (4.54x noise floor 0.0201)
; D5 verdict                             : cell-free calibration does NOT transfer: you lose more than 2x noise by skipping cells
;
; [CAUTION] an optimum for this pair sits on the design-box edge in Pressure_kPa,NozzleSpeed_mms,Zoffset_mm.
;           The true optimum may lie outside the swept range, so a
;           tie between the two conditions is partly forced by the box.
;
; Temperature: set manually in Architect UI (not in G-code)
; Target SF was NOT used to choose the cond-1 setting.
;

T1
M200=1080 ; 108 kPa
T0
G803 ; Move to safe height

M110=0 ; Set printing progress to 0%
T1
G801 ; Measure tool

#CONTOUR MODE ON [DEV PATH_DEV=0.08]

M312 ; Wait for work zone temperature

; -- well A1 | replicate 1/6 | P=108 kPa  F=5 mm/s  Z=0.100 mm --
G805[-45.785, 32.720, 2.620] ; G55 origin: A1
G55

; Changing tool to 'PSD 1'
#FLUSH WAIT
T1
G807[1, 0.002, 0.002] ; time-based start/stop delays [s]
M200=1080 ; 108 kPa
F5.000
G00 X-2.000 Y-2.500
M151 ; Engage tool for printing
Z0.100
M110=143
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well A1
; -- well B1 | replicate 2/6 | P=108 kPa  F=5 mm/s  Z=0.100 mm --
G805[-45.785, 19.640, 2.620] ; G55 origin: B1
G55
G00 Z18.400
M200=1080 ; 108 kPa
F5.000
X-2.000 Y-2.500
Z0.100
M110=286
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well B1
; -- well C1 | replicate 3/6 | P=108 kPa  F=5 mm/s  Z=0.100 mm --
G805[-45.785, 6.560, 2.620] ; G55 origin: C1
G55
G00 Z18.400
M200=1080 ; 108 kPa
F5.000
X-2.000 Y-2.500
Z0.100
M110=429
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well C1
; -- well D1 | replicate 4/6 | P=108 kPa  F=5 mm/s  Z=0.100 mm --
G805[-45.785, -6.520, 2.620] ; G55 origin: D1
G55
G00 Z18.400
M200=1080 ; 108 kPa
F5.000
X-2.000 Y-2.500
Z0.100
M110=571
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well D1
; -- well E1 | replicate 5/6 | P=108 kPa  F=5 mm/s  Z=0.100 mm --
G805[-45.785, -19.600, 2.620] ; G55 origin: E1
G55
G00 Z18.400
M200=1080 ; 108 kPa
F5.000
X-2.000 Y-2.500
Z0.100
M110=714
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well E1
; -- well F1 | replicate 6/6 | P=108 kPa  F=5 mm/s  Z=0.100 mm --
G805[-45.785, -32.680, 2.620] ; G55 origin: F1
G55
G00 Z18.400
M200=1080 ; 108 kPa
F5.000
X-2.000 Y-2.500
Z0.100
M110=857
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well F1
; CAMERA IMAGING POSITIONS
; Wells: A1, B1, C1, D1, E1, F1
; 6 replicates of P=108 kPa F=5 mm/s Z=0.1 mm in cell_gelma_10_80
;
#FLUSH WAIT
#CONTOUR MODE OFF          ; Exit tracking mode from printing
#FLUSH WAIT

T1                         ; Select slot 1
G803                       ; Move to system safe height

; --- Well A1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y53.250              ; Move XY to A1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at A1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well B1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y40.242              ; Move XY to B1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at B1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well C1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y27.234              ; Move XY to C1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at C1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well D1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y14.226              ; Move XY to D1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at D1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well E1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y1.218              ; Move XY to E1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at E1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well F1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y-11.790              ; Move XY to F1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at F1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Return home ---
G00 G54 G90 Z40.000          ; Safe Z before going home
G800                       ; Go home
M110=1000
M30
